### PR TITLE
Readme

### LINKED ISSUE #58: Readme usage section
Update usage section and explain correctly how to use it.
Add all necessary sections.

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
closed #58

### CODE REVIEW

**Review by aitorbouzas — APPROVED** [review]
LGTM
Ping @carlosDomatix

**Comment by aitorbouzas** [comment]
Well, I just noticed this is not the correct repository @emagdalenaC2i 
It's early in the morning and i'm still asleep. Please make this exact PR into `OCA-helpdesk` repository. This is not the candidate to be merge into the OCA, sorry.

**Comment by emagdalenaC2i** [comment]
I can't because I don't have permission to create a new branch or a direct pull request in https://github.com/aitorbouzas/OCA-helpdesk and if I try to create a fork it takes just the code in https://github.com/OCA/helpdesk repository

**Comment by aitorbouzas** [comment]
@emagdalenaC2i are you sure you are creating the fork from mine? @carlosDomatix and @catalin-domatix had no problem when forking it.

**Comment by emagdalenaC2i** [comment]
ok, I do not know why, but it works now (I've tried it twice before)

**Pull request closed without merging**
